### ISSUE TITLE
Unicode icon does not render properly in Windows

### ISSUE THREAD

**Issue by dragfire** [dragfire/leetup#12]
![lup2](https://user-images.githubusercontent.com/6277978/98077768-0f5cc900-1e2e-11eb-9a17-e4cd93bceb65.PNG)

Unicode icons: https://github.com/dragfire/leetup/blob/master/src/icon.rs 

Some ideas:
https://github.com/leetcode-tools/leetcode-cli/blob/master/icons/ascii.json
https://github.com/leetcode-tools/leetcode-cli/blob/master/icons/win7.json

Will need to have a fallback for command prompt!

**Comment by w93163red** [comment]
@dragfire I think the icon works fine on my terminal, I am using Windows Terminal Preview + PowerShell 7 + Cascadia code:
![image](https://user-images.githubusercontent.com/7308728/98455672-bc428900-2141-11eb-86f7-ae4d778e79a0.png)

**Comment by dragfire** [comment]
That's good to hear. I hope no one is using Command Prompt!
