### ISSUE TITLE
support cargo run

### ISSUE THREAD

**Issue by heeen** [dragfire/leetup#20]
would be nice to be able to use cargo run on the generated files, that is, optionally use cargo init to create a project and make the generated file the main.rs of that project

**Comment by dragfire** [comment]
Something like this:
```sh
leetup pick -l rust 1
````
This will create a `two-sum` directory using `cargo init two-sum` and content of `main.rs` will be generated by `leetup`.

Is my understanding correct?

**Comment by heeen** [comment]
yeah, exactly. I don't know enough about cargo, but doesn't it also support workspaces made up of multiple subprojects or something like that? Then you could have a master project and subprojects for each problem

**Comment by dragfire** [comment]
Workspaces are another way to go. But you can have `src/bin` and put any main files and run `cargo run --bin <filename_in_bin>`. Take a look at this directory. This is much simpler.

**Comment by dragfire** [comment]
Fixed #32
