### ISSUE TITLE
Filter the questions having editorial solution

### ISSUE THREAD

**Issue by tejasvi** [dragfire/leetup#36]
First off, excellent work. Using Github OAuth for login was clever. I want to filter the questions having official solutions ![image](https://user-images.githubusercontent.com/45873379/102216728-95763000-3f01-11eb-9a78-58c448021bf8.png). I tried modifying [leetcode.rs](https://github.com/dragfire/leetup/blob/master/src/service/leetcode.rs), but couldn't get it working since my rust is a bit rusty atm ;)

**Comment by dragfire** [comment]
Glad you like it. I will take a look in the next few days!
