### ISSUE TITLE
Maybe remove the error tags?

### ISSUE THREAD

**Issue by chenrui333** [dragfire/leetup#53]
It looks like the project has two abnormal tags as shown below, maybe those two can be removed? (asking because it caused some livecheck issue on the homebrew project), thanks!

![image](https://user-images.githubusercontent.com/1580956/225647874-5d4723a4-55f4-40bf-918e-54e5c6c9b5e6.png)

**Comment by dragfire** [comment]
@chenrui333 Will take a look. Curious on why we need to remove this since leetup is not on homebrew yet?

**Comment by dragfire** [comment]
Deleted. Thanks for reporting!
