### ISSUE TITLE
leetup test failure

### ISSUE THREAD

**Issue by chenrui333** [dragfire/leetup#92]
👋 while [upgrading rust to 1.77.0](https://github.com/Homebrew/homebrew-core/pull/166865), I noticed that leetup test is failing (also see the test failure in the [latest 1.2.5 release build](https://github.com/Homebrew/homebrew-core/pull/167072) as well)

```
$ /opt/homebrew/Cellar/leetup/1.2.4/bin/leetup list
Error: Reqwest(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
```

Did leetcode change the behavior requiring login to show the problem list?  (the error msg is not user friendly)

**Comment by dragfire** [comment]
<img width="749" alt="Screenshot 2024-03-27 at 8 57 30 AM" src="https://github.com/dragfire/leetup/assets/6277978/1df0cca2-4c46-4c14-b698-8ff1b2206f38">
Hey @chenrui333 yup, confirmed 😕

**Comment by chenrui333** [comment]
I see, would that make the formula useless a bit? (maybe add login check before doing the problem listing??)

**Comment by dragfire** [comment]
@chenrui333 added the check.
